# config/packages/swiftmailer.yaml

swiftmailer:
    disable_delivery: false
    transport: smtp
    encryption: tls
    auth_mode: login
    host: smtp.gmail.com
    username: slam.booking.web
    password: sb201810
    port: 587

parameters:
    env(MAILER_URL): 'gmail://slam.booking.web:sb201810@localhost'
