<?php
// App/DataFixtures/UserFixtures.php
namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use App\Entity\User;

class UserFixtures extends Fixture
{
	private $passwordEncoder;
	public function __construct(UserPasswordEncoderInterface $passwordEncoder)
	{
	$this->passwordEncoder = $passwordEncoder;
	}
    public function load(ObjectManager $manager)
    {
	foreach ($this->getIndividualData() as [$id, $username, $password, $email, $lastName, $firstName]) {
		$user = new User();
		$user->setAccountType('INDIVIDUAL');
		$user->setUserName($username);
		$user->setPassword($this->passwordEncoder->encodePassword($user, $password));
		$user->setEmail($email);
		$user->setLastName($lastName);
		$user->setFirstName($firstName);
		$user->setRoles(['ROLE_USER']);
		$manager->persist($user);
		$manager->flush();
		$reference = 'user-'.$id;
		$this->addReference($reference, $user);
	}

	foreach ($this->getOrganisationData() as [$id, $username, $password, $email, $lastName, $firstName, $uniqueName]) {
		$user = new User();
		$user->setAccountType('ORGANISATION');
		$user->setUserName($username);
		$user->setPassword($this->passwordEncoder->encodePassword($user, $password));
		$user->setEmail($email);
		$user->setLastName($lastName);
		$user->setFirstName($firstName);
		$user->setUniqueName($uniqueName);
		$user->setRoles(['ROLE_USER']);
		$manager->persist($user);
		$manager->flush();
		$reference = 'user-'.$id;
		$this->addReference($reference, $user);
	}

    }


	private function getIndividualData(): array
    {
	return [
		// $userData = [id, username, password, email, lastName, firstName]
[1, 'eric', 'eric', 'eric.willard@slam-data.net', 'WILLARD', 'Eric'],
[525, 'muriel.guillou@neotek-web.com', 'slam525', 'muriel.guillou@neotek-web.com', 'GUILLOU', 'Muriel'],
[531, 'rbourdon@rtsys.fr', 'awt423', 'rbourdon@rtsys.fr', 'BOURDON', 'Raphaël'],
[532, 'cbricaud@rtsys.fr', 'slam532', 'cbricaud@rtsys.fr', 'BRICAUD', 'C'],
[533, 'rcoquelin@rtsys.fr', 'Slam89', 'rcoquelin@rtsys.fr', 'COQUELIN', 'R'],
[534, 'ldufrechou@rtsys.fr', 'Fd_CY%Cs', 'ldufrechou@rtsys.fr', 'DUFRECHOU', 'l'],
[538, 'jkoegler@rtsys.fr', 'slam538', 'jkoegler@rtsys.fr', 'KOEGLER', 'J'],
[541, 'nmenard@rtsys.fr', 'slam541', 'nmenard@rtsys.fr', 'MENARD', 'N'],
[544, 'cnicolas@rtsys.fr', 'slam544', 'cnicolas@rtsys.fr', 'COEFFIER', 'M'],
[547, 'jean-yves.cueff@neotek-web.com', 'slam547', 'jean-yves.cueff@neotek-web.com', 'CUEFF', 'Jean-yves'],
[548, 'pierre.chevalerias@neotek-web.com', 'slam548', 'pierre.chevalerias@neotek-web.com', 'CHEVALERIAS', 'Pierre'],
[549, 'didier.clech@neotek-web.com', 'slam549', 'didier.clech@neotek-web.com', 'CLECH', 'Didier'],
[550, 'olivier.riche@neotek-web.com', 'slam550', 'olivier.riche@neotek-web.com', 'RICHE', 'Olivier'],
[551, 'manuel.lucas@neotek-web.com', 'slam551', 'manuel.lucas@neotek-web.com', 'LUCAS', 'Manuel'],
[552, 'didier.boucheton@neotek-web.com', 'slam552', 'didier.boucheton@neotek-web.com', 'BOUCHETON', 'Didier'],
[585, 'TEIXEIRA', 'slam585', 'contact@neotek-web.com', 'TEIXEIRA', 'X'],
[738, 'staps-univ-savoie', 'staps8135', 'bernard.desmaret@univ-savoie.fr', 'DESMARET', 'Bernard'],
[741, 'aurme', 'dano03', 'aurelie.merendet@univ-savoie.fr', 'MERENDET', 'Aurelie'],
[743, 'jerome.auge@univ-savoie.fr', 'slam743', 'jerome.auge@univ-savoie.fr', 'AUGE', 'Jerome'],
[744, 'pierre.bavazzano@univ-savoie.fr', 'slam744', 'pierre.bavazzano@univ-savoie.fr', 'BAVAZZANO', 'Pierre'],
[745, 'Maximilien.Bowen@univ-smb.fr', 'slam745', 'Maximilien.Bowen@univ-smb.fr', 'BOWEN', 'Maximilien'],
[746, 'phanelie.berthon@univ-savoie.fr', 'slam746', 'phanelie.berthon@univ-savoie.fr', 'BERTHON', 'Phanelie'],
[747, 'clementine.bry@univ-savoie.fr', '21241007choup', 'clementine.bry@univ-savoie.fr', 'BRY', 'Clementine'],
[748, 'nicolas.forestier@univ-savoie.fr', 'slam748', 'nicolas.forestier@univ-savoie.fr', 'FORESTIER', 'Nicolas'],
[749, 'fabienne.gillonnier@univ-savoie.fr', 'slam749', 'fabienne.gillonnier@univ-savoie.fr', 'GILLONNIER', 'Fabienne'],
[750, 'frederique.hintzy@univ-savoie.fr', 'slam750', 'frederique.hintzy@univ-savoie.fr', 'HINTZY', 'Frederique'],
[751, 'laurent.messonnier@univ-savoie.fr', 'slam751', 'laurent.messonnier@univ-savoie.fr', 'MESSONNIER', 'Laurent'],
[752, 'aurore.mionnet@univ-savoie.fr', 'slam752', 'aurore.mionnet@univ-savoie.fr', 'MIONNET', 'Aurore'],
[753, 'brigitte.petraz@univ-savoie.fr', 'slam753', 'brigitte.petraz@univ-savoie.fr', 'PETRAZ', 'Brigitte'],
[754, 'annie.rouard@univ-smb.fr', 'slam754', 'annie.rouard@univ-smb.fr', 'ROUARD', 'Annie'],
[755, 'patrice.rougier@univ-savoie.fr', 'Staps1997', 'patrice.rougier@univ-savoie.fr', 'ROUGIER', 'Patrice'],
[756, 'pierre.samozino@univ-savoie.fr', 'slam756', 'pierre.samozino@univ-savoie.fr', 'SAMOZINO', 'Pierre'],
[757, 'nicolas.varcin@univ-savoie.fr', '1r1EfC', 'nicolas.varcin@univ-savoie.fr', 'VARCIN', 'Nicolas'],
[758, 'thomas.rupp@univ-savoie.fr', 'slam758', 'thomas.rupp@univ-savoie.fr', 'RUPP', 'Thomas'],
[759, 'christophe.hourde@univ-savoie.fr', 'slam759', 'christophe.hourde@univ-savoie.fr', 'HOURDE', 'Christophe'],
[760, 'benjamin.chatel@univ-smb.fr', 'slam760', 'benjamin.chatel@univ-smb.fr', 'CHATEL', 'Benjamin'],
[761, 'florian.monjo@univ-savoie.fr', 'slam761', 'florian.monjo@univ-savoie.fr', 'MONJO', 'Florian'],
[762, 'gregoire.mitonneau@univ-savoie.fr', 'slam762', 'gregoire.mitonneau@univ-savoie.fr', 'MITONNEAU', 'Gregoire'],
[763, 'romain.terrier@univ-savoie.fr', 'slam763', 'romain.terrier@univ-savoie.fr', 'TERRIER', 'Romain'],
[765, 'sebastien.pavailler@univ-savoie.fr', 'slam765', 'sebastien.pavailler@univ-savoie.fr', 'PAVAILLER', 'Sebastien'],
[766, 'thomas.falda-buscaiot@univ-savoie.fr', 'slam766', 'thomas.falda-buscaiot@univ-savoie.fr', 'FALDA-BUSCAIOT', 'Thomas'],
[767, 'clemence.perrin-malterre@univ-savoie.fr', 'slam767', 'clemence.perrin-malterre@univ-savoie.fr', 'PERRIN-MALTERRE', 'Clemence'],
[768, 'etienne.cusin@univ-savoie.fr', 'slam768', 'etienne.cusin@univ-savoie.fr', 'CUSIN', 'Etienne'],
[813, 'cmagnier@rtsys.fr', 'slam813', 'cmagnier@rtsys.fr', 'NICOLAS', 'C'],
[843, 'RBRAKHA', 'qY7A47Fg', 'tcveureyvoroize@fft.fr', 'BRAKHA', 'R.'],
[844, 'SBRAKHA', '180245', 'suzbrakha@free.fr', 'BRAKHA', 'S.'],
[845, 'MTEST', 'mtest', 'raphael.brakha@free.fr', 'BRAKHA', 'Raphael'],
[860, 'davidpinard', 'slam860', 'david.pinard@yahoo.fr', 'PINARD', 'David'],
[864, 'adjoan79', 'adjoan79', 'franck.mousserin@ac-poitiers.fr', 'MOUSSERIN', 'Franck'],
[865, 'fralae', 'adjoan', 'mousserin.franck@wanadoo.fr', 'MOUSSERIN', 'Franck'],
[866, 'Dupeyrat', 'slam866', 'philippe.dupeyrat@ac-poitiers.fr', 'DUPEYRAT', 'Philippe'],
[867, 'sylviefrancois06@free.fr', 'moussy', 'sylviefrancois06@free.fr', 'FRANCOIS', 'Sylvie'],
[868, 'am.anthonioz@laposte.net', 'slam868', 'am.anthonioz@laposte.net', 'ANTHONIOZ', 'Tom'],
[871, 'gabriel.batel@free.fr', 'slam871', 'gabriel.batel@free.fr', 'BATEL', 'Gabriel'],
[873, 'chrisetvero.berliet@free.fr', 'slam873', 'chrisetvero.berliet@free.fr', 'BERLIET', 'Corentin'],
[874, 'annie.blachier@free.fr', 'slam874', 'annie.blachier@free.fr', 'BLACHIER', 'Annie'],
[876, 'jeremylaflamme@hotmail.fr', 'slam876', 'jeremylaflamme@hotmail.fr', 'BOURDON', 'Jérémy'],
[877, 'bouvier.jeanbaptiste@free.fr', 'slam877', 'bouvier.jeanbaptiste@free.fr', 'BOUVIER', 'Morgane'],
[880, 'charlet.francois@neuf.fr', 'slam880', 'charlet.francois@neuf.fr', 'CHARLET', 'Claudine'],
[881, 'adchazz@gmail.com', 'slam881', 'adchazz@gmail.com', 'CHAZAL', 'Adrien'],
[882, 'djludi4@gmail.com', 'slam882', 'djludi4@gmail.com', 'CHEDECAL', 'Ludovic'],
[886, 'colasjl01@gmail.com', 'COdo+01', 'colasjl01@gmail.com', 'COLAS', 'Dorian'],
[889, 'cfdrogue@free.fr', 'slam889', 'cfdrogue@free.fr', 'DROGUE', 'Catherine'],
[891, 'stefdugue@yahoo.fr', 'slam891', 'stefdugue@yahoo.fr', 'DUGUE', 'Stéphane'],
[895, 'sl.liu1@free.fr', 'slam895', 'sl.liu1@free.fr', 'FRICHITTHAVONG', 'Sin-Ly'],
[896, 'sisamone.mone@electricfil.com', 'slam896', 'sisamone.mone@electricfil.com', 'FRICHITTHAVONG', 'Sisamone'],
[897, 'tomtom01700@gmail.com', 'slam897', 'tomtom01700@gmail.com', 'FRICHITTHAVONG', 'Thomas'],
[900, 'kgudefin@hotmail.fr', 'slam900', 'kgudefin@hotmail.fr', 'GUDEFIN', 'Kevin'],
[902, 'fabiguyo@gmail.com', 'slam902', 'fabiguyo@gmail.com', 'GUYOT', 'Fabien'],
[904, 'manuelaheron@yahoo.fr', 'slam904', 'manuelaheron@yahoo.fr', 'HERON', 'Manuela'],
[905, 'vio01@hotmail.fr', 'slam905', 'vio01@hotmail.fr', 'JOLY', 'Nathan'],
[907, 'ximemalac69@gmail.com', 'slam907', 'ximemalac69@gmail.com', 'LACOUR', 'Maxime'],
[908, 'stephane.lange.sl@gmail.com', 'Tbb*Mars1', 'stephane.lange.sl@gmail.com', 'LANGE', 'Stéphane'],
[910, 'frederic.longeaud@bbox.fr', 'slam910', 'frederic.longeaud@bbox.fr', 'LONGEAUD', 'Océane'],
[911, 'cecilegregoire@hotmail.fr', 'slam911', 'cecilegregoire@hotmail.fr', 'LONGIN', 'Noémis'],
[912, 'mylenebliard@msn.com', 'slam912', 'mylenebliard@msn.com', 'LUCIANI', 'Thomas'],
[915, 'lopez.mathilde@neuf.fr', 'slam915', 'lopez.mathilde@neuf.fr', 'MARTIN-LOPEZ', 'Emma'],
[917, 'Elodie.moro@hotmail.fr', 'slam917', 'Elodie.moro@hotmail.fr', 'MORO', 'Elodie'],
[918, 'catherine.moulart@orange.fr', 'slam918', 'catherine.moulart@orange.fr', 'MOULART', 'Catherine'],
[919, 'j.muslewski@hotmail.fr', 'slam919', 'j.muslewski@hotmail.fr', 'MUSLEWSKI', 'Clara'],
[920, 'cathy.pain@wibox.fr', 'slam920', 'cathy.pain@wibox.fr', 'PAIN', 'Alban'],
[921, 'perraudgael@yahoo.fr', 'slam921', 'perraudgael@yahoo.fr', 'PERRAUD', 'Gaël'],
[922, 'petitsteph@neuf.fr', 'slam922', 'petitsteph@neuf.fr', 'PETIT', 'Lilou'],
[923, 'marinechristophe@yahoo.fr', 'slam923', 'marinechristophe@yahoo.fr', 'PONS', 'Ilona'],
[924, 'virginieprat@ouimail.fr', 'slam924', 'virginieprat@ouimail.fr', 'PRAT', 'Charly'],
[926, 'philippe.rb@wanadoo.fr', 'slam926', 'philippe.rb@wanadoo.fr', 'RABETTE', 'Sylvain'],
[930, 'fabien.roche@socgen.com', 'slam930', 'fabien.roche@socgen.com', 'ROCHE', 'Louis-augustin'],
[931, 'hugoseiller@hotmail.com', 'slam931', 'hugoseiller@hotmail.com', 'SEILLER', 'Hugo'],
[934, 'hamdi-unal@hotmail.fr', 'slam934', 'hamdi-unal@hotmail.fr', 'UNAL', 'Elif'],
[936, 'verdier.gregory@freesbee.fr', 'slam936', 'verdier.gregory@freesbee.fr', 'VERDIER', 'Alexandre'],
[942, 'philippe.roger@ac-poitiers.fr', 'slam942', 'philippe.roger@ac-poitiers.fr', 'ROGER', 'Philippe'],
[946, 'CBERAL', 'slam946', 'slam-946@slam-data.net', 'BERAL', 'Famille'],
[954, 'JGUICHARD', 'slam954', 'slam-954@slam-data.net', 'GUICHARD', 'Jérôme'],
[956, 'PJOUBERT', 'slam956', 'slam-956@slam-data.net', 'JOUBERT', 'Pierre'],
[959, 'BPEZET', 'slam959', 'slam-959@slam-data.net', 'PEZET', 'Famille'],
[961, 'PPOPELIN', 'slam961', 'slam-961@slam-data.net', 'POPELIN', 'Famille'],
[962, 'SROLLAND', 'slam962', 'slam-962@slam-data.net', 'ROLLAND', 'Sébastien'],
[965, 'JSORIANO', 'slam965', 'slam-965@slam-data.net', 'SORIANO', 'Jérôme'],
[969, 'benedicte.vincent@ac-poitiers.fr', 'slam969', 'benedicte.vincent@ac-poitiers.fr', 'VINCENT', 'Benedicte'],
[970, 'erwan.autret@ac-poitiers.fr', 'slam970', 'erwan.autret@ac-poitiers.fr', 'AUTRET', 'Erwan'],
[973, 'Annabelle-Sever.Prouteau@ac-poitiers.fr', 'slam973', 'Annabelle-Sever.Prouteau@ac-poitiers.fr', 'PROUTEAU', 'Annabelle'],
[974, 'Anne.Ratier@ac-poitiers.fr', 'slam974', 'Anne.Ratier@ac-poitiers.fr', 'RATIER', 'Anne'],
[975, 'aurelie.egoroff@ac-poitiers.fr', 'lucasmathis', 'aurelie.egoroff@ac-poitiers.fr', 'EGOROFF', 'Aurelie'],
[976, 'Bernard.Sling@ac-poitiers.fr', 'slam976', 'Bernard.Sling@ac-poitiers.fr', 'SLING', 'Bernard'],
[977, 'cdi.c-font-niort@ac-poitiers.fr', 'slam977', 'cdi.c-font-niort@ac-poitiers.fr', 'BAALI', 'Isabelle'],
[978, 'Celine.Macke@ac-poitiers.fr', '140564', 'Celine.Macke@ac-poitiers.fr', 'MACKE', 'Celine'],
[979, 'Christian.Cartron@ac-poitiers.fr', 'slam979', 'Christian.Cartron@ac-poitiers.fr', 'CARTRON', 'Christian'],
[981, 'Christophe.Morin1@ac-poitiers.fr', 'slam981', 'Christophe.Morin1@ac-poitiers.fr', 'CLAY', 'Jean-michel et ugo'],
[982, 'Chrystelle.Zouaghi@ac-poitiers.fr', 'slam982', 'Chrystelle.Zouaghi@ac-poitiers.fr', 'ZOUAGHI', 'Chrystelle'],
[983, 'Cyrille-Victor.Poignand@ac-poitiers.fr', 'slam983', 'Cyrille-Victor.Poignand@ac-poitiers.fr', 'POIGNAND', 'Cyrille-victor'],
[985, 'Delphine.Godin-Guichard2@ac-poitiers.fr', 'slam985', 'Delphine.Godin-Guichard2@ac-poitiers.fr', 'GODIN-GUICHARD', 'Delphine'],
[987, 'Laura.Goubot@ac-poitiers.fr', 'liameliott', 'Laura.Goubot@ac-poitiers.fr', 'GOUBOT', 'Laura'],
[988, 'Irene-Christine.Pereira@ac-poitiers.fr', 'slam988', 'Irene-Christine.Pereira@ac-poitiers.fr', 'PEREIRA', 'Irene-christine'],
[989, 'Isabelle.Meyer1@ac-poitiers.fr', 'slam989', 'Isabelle.Meyer1@ac-poitiers.fr', 'MEYER', 'Isabelle'],
[990, 'julie.desblancs@ac-poitiers.fr', 'slam990', 'julie.desblancs@ac-poitiers.fr', 'DESBLANCS', 'Julie'],
[993, 'Karine.Delattre@ac-poitiers.fr', 'slam993', 'Karine.Delattre@ac-poitiers.fr', 'DELATTRE', 'Karine'],
[994, 'Katel.Babin@ac-poitiers.fr', '17121980', 'Katel.Babin@ac-poitiers.fr', 'BABIN', 'Katel'],
[996, 'laurie@leoty.com', 'slam996', 'laurie@leoty.com', 'LEOTY', 'Laurie'],
[998, 'Louis-Bertrand.Thibal-Maziat@ac-poitiers.fr', 'slam998', 'Louis-Bertrand.Thibal-Maziat@ac-poitiers.fr', 'THIBAL-MAZIAT', 'Louis-bertrand'],
[999, 'Lucie.Millot@ac-poitiers.fr', 'slam999', 'Lucie.Millot@ac-poitiers.fr', 'MILLOT', 'Lucie'],
[1000, 'M.christin.Moreau@ac-poitiers.fr', 'slam1000', 'M.christin.Moreau@ac-poitiers.fr', 'CHRISTIN-MOREAU', 'Marie-Christine'],
[1002, 'Olivier.Mathian@ac-poitiers.fr', 'slam1002', 'Olivier.Mathian@ac-poitiers.fr', 'MATHIAN', 'Olivier'],
[1003, 'Pascal.Plantiveau@ac-poitiers.fr', '1956football', 'Pascal.Plantiveau@ac-poitiers.fr', 'PLANTIVEAU', 'Pascal'],
[1004, 'Pascale.Daugas@ac-poitiers.fr', 'slam1004', 'Pascale.Daugas@ac-poitiers.fr', 'DAUGAS', 'Pascale'],
[1005, 'bruno.guerineau@cg79.fr', 'slam1005', 'bruno.guerineau@cg79.fr', 'GUERINEAU', 'Bruno'],
[1006, 'joel.ausserve@cg79.fr', 'slam1006', 'joel.ausserve@cg79.fr', 'AUSSERVE', 'Joel'],
[1007, 'patricia.cluzel@ac-poitiers.fr', 'patou1', 'patricia.cluzel@ac-poitiers.fr', 'CLUZEL', 'Patricia'],
[1009, 'rbordeaux', 'gribou79', 'regis.bordeaux@ac-poitiers.fr', 'BORDEAUX', 'Regis'],
[1010, 'Consuelo.Ropero@ac-poitiers.fr', 'slam1010', 'Consuelo.Ropero@ac-poitiers.fr', 'ROPERO', 'Consuelo'],
[1011, 'stephanie-miche.rouquette@ac-poitiers.fr', 'slam1011', 'stephanie-miche.Rouquette@ac-poitiers.fr', 'MICHE-ROUQUETTE', 'Stéphanie'],
[1012, 'Sandrine.Dumas@ac-poitiers.fr', 'slam1012', 'Sandrine.Dumas@ac-poitiers.fr', 'DUMAS', 'Sandrine'],
[1013, 'Serge.Zilberman@ac-poitiers.fr', 'slam1013', 'Serge.Zilberman@ac-poitiers.fr', 'ZILBERMAN', 'Serge'],
[1014, 'Sophie.Lefer@ac-poitiers.fr', 'slam1014', 'Sophie.Lefer@ac-poitiers.fr', 'LEFER', 'Sophie'],
[1015, 'sophie.mercier@ac-poitiers.fr', 'slam1015', 'sophie.mercier@ac-poitiers.fr', 'MERCIER', 'Sophie'],
[1016, 'Valerie.Morales@ac-poitiers.fr', 'slam1016', 'Valerie.Morales@ac-poitiers.fr', 'POPINET', 'Valérie'],
[1017, 'Isabelle.Verdeau@ac-poitiers.fr', 'slam1017', 'Isabelle.Verdeau@ac-poitiers.fr', 'VERDEAU', 'Isabelle'],
[1018, 'virginie.pelletier@ac-poitiers.fr', 'slam1018', 'virginie.pelletier@ac-poitiers.fr', 'PELLETIER', 'Virginie'],
[1024, 'veron.c', 'slam1024', 'slam-1024@slam-data.net', 'VERON', 'C'],
[1025, 'piel.l', 'slam1025', 'slam-1025@slam-data.net', 'PIEL', 'I'],
[1026, 'leurent.a', 'slam1026', 'slam-1026@slam-data.net', 'LEURENT', 'A'],
[1027, 'chatel.c', 'slam1027', 'slam-1027@slam-data.net', 'CHATEL', 'C'],
[1029, 'labelliere.c', 'slam1029', 'slam-1029@slam-data.net', 'DE LA BELLIERE', 'C'],
[1030, 'brossier.n', 'slam1030', 'slam-1030@slam-data.net', 'BROSSIER', 'N'],
[1037, 'Chatal.g', 'slam1037', 'slam-1037@slam-data.net', 'CHATAL', 'G'],
[1039, 'deGaalon.ma', 'slam1039', 'slam-1039@slam-data.net', 'DE GAALON', 'MA'],
[1040, 'Ferron.j', 'slam1040', 'slam-1040@slam-data.net', 'FERRON', 'JM'],
[1041, 'Goulaouic.s', 'slam1041', 'slam-1041@slam-data.net', 'GOULAOUIC', 'S'],
[1042, 'Filâtre.n', 'slam1042', 'slam-1042@slam-data.net', 'FILATRE', 'N'],
[1044, 'Lefloch.j', 'slam1044', 'slam-1044@slam-data.net', 'LEFLOCH', 'J'],
[1045, 'Monnier.f', 'slam1045', 'slam-1045@slam-data.net', 'MONNIER', 'F'],
[1046, 'Motta.m', 'slam1046', 'slam-1046@slam-data.net', 'MOTTA', 'M'],
[1047, 'Potiez.e', 'slam1047', 'slam-1047@slam-data.net', 'POTIEZ', 'E'],
[1048, 'Simonneaux.b', 'slam1048', 'slam-1048@slam-data.net', 'SIMONNEAUX', 'B'],
[1049, 'Tourillon.n', 'slam1049', 'slam-1049@slam-data.net', 'TOURILLON', 'N'],
[1050, 'Tannoux.p', 'slam1050', 'slam-1050@slam-data.net', 'TANNOUX', 'P'],
[1051, 'Amilcaro.c', 'slam1051', 'slam-1051@slam-data.net', 'AMILCARO', 'C'],
[1052, 'Munoz.o', 'slam1052', 'slam-1052@slam-data.net', 'MUNOZ', 'O'],
[1056, 'dan.bouillet@hotmail.fr', 'slam1056', 'dan.bouillet@hotmail.fr', 'BOUILLET', 'Daniel'],
[1070, 'Neotek', 'slam1070', 'remy.goudedranche@neotek-web.com', 'GOUDEDRANCHE', 'Remy'],
[1081, 'arthur.peyrard@univ-smb.fr', 'Azerty01', 'Arthur.Peyrard@univ-smb.fr', 'PEYRARD', 'Arthur'],
[1082, 'MONROLIN SYLVIE', 'slam1082', 'sylvie.monrolin@gmail.com', 'MONROLIN', 'Sylvie'],
[1083, 'Eilvys70', 'slam1083', 'slam-1083@slam-data.net', 'MONROLIN', 'Sylvie'],
[1084, 'FREDZOUILLE', 'slam1084', 'fred-girardin@orange.fr', 'GIRARDIN', 'Frederic'],
[1085, '2cv1957', 'slam', 'calou.amandine@orange.fr', 'BONNOT', 'Pascal'],
[1086, '101274', 'slam1086', 'mariedetroye@wanadoo.fr', 'DETROYE', 'Marie'],
[1088, 'Mc fly', 'slam1088', 'cccd@sfr.fr', 'CHARLET', 'Christophe'],
[1089, 'JustineB', 'cuoo75', 'bugnetjustine@yahoo.fr', 'BUGNET', 'Justine'],
[1091, 'DROPERT', 'slam1091', 'slam-1091@slam-data.net', 'ROPERT', 'Dominique'],
[1092, '2512CL', 'slam1092', 'christellelemerle@gmail.com', 'LEMERLE', 'Christelle'],
[1094, 'AUGUSTIN', 'slam1094', 'dorian.grave70@gmail.com', 'GRAVE', 'Dorian'],
[1096, 'jean-luc.sommer@univ-fcomte.fr', 'a3nsuti8', 'jean-luc.sommer@univ-fcomte.fr', 'SOMMER', 'Jean-luc'],
[1097, 'a.messelot@laposte.net', 'nu7eaczi', 'a.messelot@laposte.net', 'MESSELOT', 'Alain'],
[1103, 'nbillery@orange.fr', 'slam1103', 'nbillery@orange.fr', 'BILLERY', 'Nathan'],
[1104, 'daniel.bolot@wanadoo.fr', 'slam1104', 'daniel.bolot@wanadoo.fr', 'BOLOT', 'Daniel'],
[1105, 'pbnv@orange.fr', 'slam1105', 'pbnv@orange.fr', 'BONNAVENTURE', 'Pierre'],
[1106, 'roland.chapuis0991@orange.fr', 'slam1106', 'roland.chapuis0991@orange.fr', 'CHAPUIS', 'Roland'],
[1107, 'm.couillaud@orange.fr', 'slam1107', 'm.couillaud@orange.fr', 'COUILLAUD', 'Monique'],
[1108, 'jacques.de-sy@orange.fr', 'slam1108', 'jacques.de-sy@orange.fr', 'DE-SY', 'Jacques'],
[1109, 'demaret_sebastien@yahoo.fr', 'slam1109', 'demaret_sebastien@yahoo.fr', 'DEMARET', 'Sébastien'],
[1110, 'fdemont@dutruy.com', 'slam1110', 'fdemont@dutruy.com', 'DEMONT', 'François'],
[1111, 'Jc.Druet@laposte.Net', 'slam1111', 'jc.druet@laposte.net', 'DRUET', 'Jean-christophe'],
[1112, 'jp.druet@free.fr', 'slam1112', 'jp.druet@free.fr', 'DRUET', 'Jean-pierre'],
[1113, 'plfeenstra@gmail.com', 'leunis57', 'plfeenstra@gmail.com', 'FEENSTRA', 'Peter'],
[1114, 'y.folley@orange.fr', 'slam1114', 'y.folley@orange.fr', 'FOLLEY', 'Yves'],
[1115, 'Stéphane.gray@sfr.fr', 'slam1115', 'stephane.gray@sfr.fr', 'GENIN', 'Stéphane'],
[1116, 'clubcoxi@yahoo.fr', 'slam1116', 'clubcoxi@yahoo.fr', 'GRANDJEAN', 'Christophe'],
[1117, 'p.kaiser@free.fr', 'slam1117', 'p.kaiser@free.fr', 'KAISER', 'Pierre'],
[1118, 'thierry.kubiak@wanadoo.fr', 'slam1118', 'thierry.kubiak@wanadoo.fr', 'KUBIAK', 'Thierry'],
[1119, 'glimonier@wanadoo.fr', 'slam1119', 'glimonier@wanadoo.fr', 'LIMONIER', 'Gilles'],
[1120, 'gmaignan2@wanadoo.fr', 'slam1120', 'gmaignan2@wanadoo.fr', 'MAIGNAN', 'Georges'],
[1121, 'bernard.meurisse@hotmail.fr', 'slam1121', 'bernard.meurisse@hotmail.fr', 'MEURISSE', 'Bernard'],
[1122, 'ougierroux@yahoo.fr', 'slam1122', 'ougierroux@yahoo.fr', 'OUGIER', 'Jeanne-antide'],
[1123, 'boubout70@orange.fr', 'slam1123', 'boubout70@orange.fr', 'OUGIER', 'Robert'],
[1124, 'philippe.outrey@hotmail.fr', 'slam1124', 'philippe.outrey@hotmail.fr', 'OUTREY', 'Clarisse'],
[1125, 'j.sommer@hotmail.fr', 'slam1125', 'j.sommer@hotmail.fr', 'SOMMER', 'Jules'],
[1126, 'm.sommer@hotmail.fr', 'slam1126', 'm.sommer@hotmail.fr', 'SOMMER', 'Maxime'],
[1127, 'dtartrat@laposte.net', 'slam1127', 'dtartrat@laposte.net', 'TARTRAT', 'Danièle'],
[1128, 'stephanevera@orange.fr ', 'slam1128', 'stephanevera@orange.fr', 'VERA', 'Stéphane'],
[1129, 'anthonin.verdy@aliceadsl.fr', 'slam1129', 'anthonin.verdy@aliceadsl.fr', 'VERDY', 'Anthonin'],
[1130, 'olivier.virely@jgaviation.eu', 'slam1130', 'olivier.virely@jgaviation.eu', 'VIRELY', 'Olivier'],
[1131, 'yousfi_ahmed@hotmail.com', 'kate7277', 'yousfi_ahmed@hotmail.com', 'YOUSFI', 'Ahmed'],
[1132, 'MENIPAO', 'azerty25', 'menisan@voila.fr', 'MENICUCCI', 'Aimeric'],
[1140, 'LaureDesvard', 'slam1140', 'slam-1140@slam-data.net', 'DESVARD', 'Laure'],
[1141, 'ThomasBeauchamp', 'slam1141', 'slam-1141@slam-data.net', 'BEAUCHAMP', 'Thomas'],
[1142, 'Bmdfamily', 'slam1142', 'laurencebossy@yahoo.fr', 'DIDRI', 'Romane'],
[1143, 'Ibandars', 'slam1143', 'philippe.dars@ac-besancon.fr', 'DARS', 'Philippe'],
[1144, 'antoinedu70', 'slam1144', 'yamakasi70.braillard@hotmail.fr', 'BRAILLARD', 'Antoine'],
[1145, 'JCOINGROY', 'slam1145', 'slam-1145@slam-data.net', 'COING ROY', 'Joelle'],
[1147, 'piermax25170', 'slam1147', 'gillesbarthod@orange.fr', 'BARTHOD', 'Pierre'],
[1151, 'Paulmartin', 'slam1151', 'xavier.hubner@gmail.com', 'HUBNER', 'Paul'],
[1153, 'AgnesBoeuf', 'slam1153', 'slam-1153@slam-data.net', 'BŒUF', 'Agnès'],
[1154, 'LauraWinn', 'slam1154', 'slam-1154@slam-data.net', 'WINN', 'Laura'],
[1155, 'AmelieDhurlaborde', 'slam1155', 'slam-1155@slam-data.net', 'DHURLABORDE', 'Amélie'],
[1159, 'GuillaumeA', 'slam1159', 'a.guillaume17@wanadoo.fr', 'GUILLAUME', 'Alain'],
[1171, 'Pierre Barthod', 'slam1171', 'pierrebarthod25@gmail.com', 'BARTHOD', 'Pierre'],
[1172, 'phchenevier', 'slam1172', 'slam-1172@slam-data.net', 'CHENEVIER', 'Ph'],
[1173, 'adam2006', 'slam1173', 'david.boillot@wanadoo.fr', 'BOILLOT', 'Adam'],
[1178, 'vialliguie', 'slam1178', 'vincent.alliguie@sfr.fr', 'ALLIGUIE', 'Vincent'],
[1179, 'chbalme', 'balmax', 'balmax@numericable.fr', 'MORIN', 'Christophe'],
[1180, 'ambargain', 'mercure14', 'amaury.bargain@orange.fr', 'BARGAIN', 'Amaury'],
[1182, 'frbusnel', 'slam1182', 'franck.busnel@orange.fr', 'BUSNEL', 'Franck'],
[1183, 'jecaussade', 'slam1183', 'jeremy.caussade@airbus.com', 'CAUSSADE', 'Jeremy'],
[1184, 'bedarolles', 'soules32', 'bernard.darolles@wanadoo.fr', 'DAROLLES', 'Bernard'],
[1185, 'jadarolles', 'slam1185', 'jacques@darolles.com', 'DAROLLES', 'Jacques'],
[1186, 'videlaborderie', 'vd!1687', 'vdelab@melix.org', 'DE LA BORDERIE', 'V'],
[1187, 'jefraumont', 'solene00', 'jeanmarc.fraumont@free.fr', 'FRAUMONT', 'Jean-Marc'],
[1188, 'logendebien', '32220', 'l.gendebien@gmail.com', 'GENDEBIEN', 'l'],
[1189, 'hegielen', 'slam1189', 'herbert.gielen@gmail.com', 'GIELEN', 'Herbert'],
[1190, 'hegounot', '29zvwbp', 'herve.gounot@neuf.fr', 'GOUNOT', 'Herve'],
[1193, 'milamarque', 'slam1193', 'mmlamarque@gmail.com', 'LAMARQUE', 'M'],
[1194, 'chlhuillier', 'slam1194', 'charles.lhuillier@airbus.com', 'LHUILLIER', 'Charles'],
[1196, 'humarty', 'slam1196', 'huguesmarty82@gmail.com', 'MARTY', 'Hugues'],
[1197, 'jenabonne', 'slam1197', 'jnabonne@aol.com', 'NABONNE', 'J'],
[1198, 'maollivier', 'slam1198', 'ollivier.matthieu@gmail.com', 'MATTHIEU', 'Ollivier'],
[1201, 'mapuntous', 'mppikachu', 'mariepuntous@hotmail.com', 'PUNTOUS', 'Marie'],
[1202, 'repuntous', 'slam1202', 'imipuntous.r@wanadoo.fr', 'IMIPUNTOUS', 'R'],
[1203, 'ritisseyre', 'slam1203', 'richard-michele.tisseyre@orange.fr', 'TISSEYRE', 'Richard-michele'],
[1212, 'jefajolles', 'slam1212', 'jean.fajolles@sfr.fr', 'FAJOLLES', 'Jean'],
[1213, 'frhoussard', 'slam1213', 'f.houssard@wanadoo.fr', 'HOUSSARD', 'F'],
[1214, 'menfin', 'slam1214', 'mauvilly.aurore@wanadoo.fr', 'MAUVILLY', 'Aurore'],
[1216, 'phdorval', 'avionulm', 'philippe.dorval.aviation@gmail.com', 'DORVAL', 'Philippe'],
[1217, 'stcaumartin', 'slam1217', 'st.caumartin@orange.fr', 'CAUMARTIN', 'St'],
[1237, 'Ivan', 'madrid2003', 'ivanborbolla41@gmail.com', 'BORBOLLA SANCHEZ', 'Ivan-benedicto'],
[1241, 'ctroussard@rtsys.fr', 'slam1241', 'ctroussard@rtsys.fr', 'TROUSSARD', 'Corentin'],
[1246, 'mibertin', 'slam1246', 'mh.bertin@wanadoo.fr', 'BERTIN', 'Mh'],
[1253, 'chcoldefy', 'slam1253', 'chantal.coldefy@free.fr', 'COLDEFY', 'Chantal'],
[1254, 'gautrot', 'lloris', 'jbgautrot@yahoo.fr', 'GAUTROT', 'Yves'],
[1276, 'jean-pierre.beguin@univ-smb.fr', 'slam1276', 'jean-pierre.beguin@univ-smb.fr', 'BEGUIN', 'Jean-pierre'],
[1282, 'daniel.j', 'slam1282', 'daniel.j@moka-sacrecoeur.fr', 'J', 'Daniel'],
[1286, 'christophe.batel@free.fr', 'slam1286', 'christophe.batel@free.fr', 'BATEL', 'Christophe'],
[1290, 'SFORGE', 'slam1290', 'slam-1290@slam-data.net', 'FORGE', 'Sébastien'],
[1292, 'ACATHIGNOL', 'slam1292', 'slam-1292@slam-data.net', 'CATHIGNOL', 'Augustin'],
[1293, 'SMOULERES', 'slam1293', 'slam-1293@slam-data.net', 'MOULERES', 'Stéphanie'],
[1305, 'artheo', 'slam1305', 'cyrilcyralex@wanadoo.fr', 'BOUDAUX', 'Theo'],
[1309, 'ervine.ruas@free.fr', 'slam1309', 'ervine.ruas@free.fr', 'RUAS', 'Ervine'],
[1310, 'nath4.chevalier@laposte.net', 'slam1310', 'nath4.chevalier@laposte.net', 'CHEVALIER', 'Nathalie'],
[1312, 'kiki21dudu', 'slam1312', 'duvernay.jerome@orange.fr', 'DUVERNAY', 'Killian'],
[1313, 'totoffy24', 'slam1313', 'christophe-tpsloriot@orange.fr', 'RIBEIRO', 'Christophe'],
[1314, 'virginie.lagarde@insa-lyon.fr', 'slam1314', 'virginie.lagarde@insa-lyon.fr', 'LAGARDE', 'Virginie'],
[1315, 'Clayteam69@gmail.com', 'slam1315', 'Clayteam69@gmail.com', 'MAGNIER', 'C'],
[1316, 'cluzel.jules@gmail.com', 'kolajtm', 'cluzel.jules@gmail.com', 'CLUZEL', 'Jules'],
[1317, 'jean.riviere@univ-smb.fr', 'slam1317', 'Jean.Riviere@univ-smb.fr', 'RIVIERE', 'Jean'],
[1366, 'nthihien@hotmail.com', 'slam1366', 'nthihien@hotmail.com', 'LANGE', 'Christine'],
[1368, 'hoang.julien@free.fr', 'slam1368', 'hoang.julien@free.fr', 'HOANG', 'Julien'],
[1369, 'vlhoang@hotmail.fr', 'slam1369', 'vlhoang@hotmail.fr', 'HOANG', 'Van-Lath'],
[1374, 'DJOKO', 'slam1374', 'vincent.ballot@bvb-france.com', 'BALLOT', 'Vincent'],
[1375, 'Phduc', 'slam1375', 'philippeduc9@gmail.com', 'DUC', 'Philippe'],
[1376, 'Dohourtal', 'johnantho21', 'dominique-hourtal@orange.fr', 'HOURTAL', 'Dominique'],
[1377, 'xacombes', 'monabaika', 'xcombes@free.fr', 'COMBES', 'X'],
[1378, 'jelis', 'surfer31', 'jp.lis@hotmail.fr', 'LIS', 'J-P'],
[1383, 'cmarceau@plasticomnium.com', 'slam1383', 'cmarceau@plasticomnium.com', 'MARCEAU', 'Christophe'],
[1386, 'AgnesNazon', 'slam1386', 'slam-1386@slam-data.net', 'NAZON', 'Agnès'],
[1387, 'ChristopheBerthuet', 'slam1387', 'slam-1387@slam-data.net', 'BERTHUET', 'Christophe'],
[1388, 'ClaraGiannechini', 'slam1388', 'slam-1388@slam-data.net', 'GIANNECHINI', 'Clara'],
[1389, 'LiseGauGr1', 'slam1389', 'slam-1389@slam-data.net', 'GAUGR1', 'Lise'],
[1391, 'DidierDesvard', 'slam1391', 'slam-1391@slam-data.net', 'DESVARD', 'Didier'],
[1393, 'LiseGauGr2', 'slam1393', 'slam-1393@slam-data.net', 'GAUGR2', 'Lise'],
[1394, 'JulieLognon', 'slam1394', 'slam-1394@slam-data.net', 'LOGNON', 'Julie'],
[1395, 'Valentin', 'slam1395', 'annaletondal@gmail.com', 'LETONDAL', 'Valentin'],
[1396, 'Regane', 'slam1396', 'barth.aurore@orange.fr', 'BARTH', 'Louis'],
[1400, 'ThomaSornaY', 'slam1400', 'gaillard.francis@neuf.fr', 'GAILLARD', 'Thomas'],
[1401, 'Jenn', 'slam1401', 'jennifer.hego@orange.fr', 'HEGO', 'Jennifer'],
[1402, 'poupetto@hotmail.fr', 'slam1402', 'poupetto@hotmail.fr', 'CROZET', 'Olga'],
[1403, 'cromonguy@gmail.com', 'slam1403', 'cromonguy@gmail.com', 'CROZET', 'Guy'],
[1409, 'ludange', 'slam1409', 'ludovine.bullin@gmail.com', 'BONNET', 'Ludovine'],
[1410, 'Vincent D', 'slam1410', 'vincentdbv@hotmail.fr', 'D', 'Vincent'],
[1411, 'tazyannick', 'slam1411', 'tazyannick@yahoo.fr', 'TAZY', 'Annick'],
[1412, 'gaetan', 'slam1412', 'gaetan.mitanchez@6-incendie.eu', 'MITANCHEZ', 'Gaetan'],
[1413, 'robinyacout', 'slam1413', 'robin.yacout@gmail.com', 'YACOUT', 'Robin'],
[1414, 'fabien dufour', 'slam1414', 'faduf@hotmail.fr', 'DUF', 'Fabien'],
[1425, 'lola.soubeyroux@ac-poitiers.fr', 'slam1425', 'lola.soubeyroux@ac-poitiers.fr', 'SOUBEYROUX', 'Lola'],
[1431, 'ejames', 'slam1431', 'slam-1431@slam-data.net', 'JAMES', 'E'],
[1432, 'araynaud', 'slam1432', 'slam-1432@slam-data.net', 'RAYNAUD', 'A'],
[1433, 'edelon', 'slam1433', 'slam-1433@slam-data.net', 'DELON', 'Eric'],
[1434, 'lleroy', 'slam1434', 'slam-1434@slam-data.net', 'LEROY', 'Luc'],
[1435, 'ysouyris', 'slam1435', 'slam-1435@slam-data.net', 'SOUYRIS', 'Yann'],
[1436, 'sbenello', 'slam1436', 'slam-1436@slam-data.net', 'BENELLO', 'Sylvie'],
[1437, 'pmahauden', 'slam1437', 'slam-1437@slam-data.net', 'MAHAUDEN', 'Pierre'],
[1438, 'ncouffin', 'slam1438', 'slam-1438@slam-data.net', 'COUFFIN', 'Nicole'],
[1441, 'mcollet', 'slam1441', 'slam-1441@slam-data.net', 'COLLET', 'Mélanie'],
[1442, 'valentinbaligand', 'slam1442', 'valentinbaligand@gmail.com', 'BALIGAND', 'Valentin'],
[1443, 'guillaumedesbourbes', 'slam1443', 'dessg71@hotmail.fr', 'DESBOURBES', 'Guillaume'],
[1444, 'gerardmensoif', 'slam1444', 'clement.garraud@gmail.com', 'GARRAUD', 'Clement'],
[1445, 'jc71', 'slam1445', 'gordatjc@gmail.com', 'GORDAT', 'J-C'],
[1446, 'levieuxmichel', 'slam1446', 'michel.levieux199@orange.fr', 'LEVIEUX', 'Michel'],
[1447, 'thierry71', 'slam1447', 'thierry.malosse@free.fr', 'MALOSSE', 'Thierry'],
[1448, 'marius71600', 'slam1448', 'boucherie71600@gmail.com', 'PAUTONNIER', 'Marius'],
[1449, 'aubretdavid', 'slam1449', 'david.aubret71@gmail.com', 'AUBRET', 'David'],
[1450, 'bernardchristophe', 'slam1450', 'coco71160@msn.com', 'BERNARD', 'Christophe'],
[1451, 'deguinsylvain', 'slam1451', 'sylvaind71@gmail.com', 'DEGUIN', 'Sylvain'],
[1452, 'duliegebenoit', 'slam1452', 'bduliege@etu.isara.fr', 'DULIEGE', 'Benoit'],
[1453, 'simonpacaud', 'slam1453', 'simonpacaud@hotmail.fr', 'PACAUD', 'Simon'],
[1454, 'pab71', 'slam1454', 'pab71@hotmail.fr', 'BAUDOUX', 'Pierre-Antoine'],
[1457, 'franckney', 'Salsa0707', 'franck.ney@gmail.com', 'NEY', 'Franck'],
[1459, 'flothibert', 'slam1459', 'flo.thibert@gmail.com', 'THIBERT', 'Florent'],
[1460, 'fableggieri', 'slam1460', 'fableggieri@hotmail.com', 'LEGGIERI', 'Fabien'],
[1462, 'f2bo@hotmail.fr', 'slam1462', 'f2bo@hotmail.fr', 'DEBAUD', 'Florent'],
[1464, 'bourgeong', 'slam1464', 'guillaume.bourgeon@laposte.net', 'BOURGEON', 'Guillaume'],
[1468, 'jordan0411', 'slam1468', 'jordan0411@hotmail.fr', 'JORDAN', 'Martin'],
[1471, 'louis1990', 'slam1471', 'louisdemontgrand@me.com', 'DE MONTGRAND', 'Louis'],
[1473, 'Jdamoison', 'slam1473', 'slam-1473@slam-data.net', 'DAMOISON', 'Jerôme'],
[1474, 'ludovic7193', 'slam1474', 'ludovic.champet@free.fr', 'CHAMPET', 'Ludovic'],
[1476, 'franckfourrier', 'slam1476', 'samislever@hotmail.com', 'FOURRIER', 'Franck'],
[1477, 'jacky', 'slam1477', 'brigitte.mamessier@orange.fr', 'MAMESSIER', 'Jacky'],
[1478, 'anthonycollodin', 'slam1478', 'anthony.collodin@orange.fr', 'ANTHONY', 'Collodin'],
[1479, 'jllapandry', 'slam1479', 'jean-luc.lapandry@terreal.com', 'LAPANDRY', 'Jean-luc'],
[1483, 'joaophil ', 'slam1483', 'joaophil@wanadoo.fr', 'MARTIN', 'Jean-Philippe'],
[1485, 'damien', 'slam1485', 'damienbuchet01@gmail.com', 'BUCHET', 'Damien'],
[1486, 'rachelheintz', 'slam1486', 'heintz.rachel@wanadoo.fr', 'HEINTZ', 'Rachel'],
[1487, 'florians', 'slam1487', 'f.sivignon@hotmail.fr', 'SIVIGNON', 'Florian'],
[1488, 'fabienc', 'slam1488', 'fab.combaluzier@gmail.com', 'COMBALUZIER', 'Fabien'],
[1489, 'fchevrot', 'slam1489', 'fchevrot67@gmail.com', 'CHEVROT', 'Franck'],
[1490, 'jtramoy', 'slam1490', 'jeremy.tramoy@gmail.com', 'TRAMOY', 'Jeremy'],
[1496, 'dorineR', 'slam1496', 'raydorine@gmail.com', 'RAY', 'Dorine'],
[1497, 'sebastienp', 'slam1497', 'seb.poll@hotmail.fr', 'POLLIER', 'Sebastien'],
[1499, 'melaniet', 'slam1499', 'turland.melanie@neuf.fr', 'TURLAND', 'Melanie'],
[1500, 'guillaumed', 'slam1500', 'desbourbes.guillaume@orange.fr', 'DESBOURBES', 'Guillaume'],
[1502, 'mickaelb', 'slam1502', 'rockfmr@hotmail.fr', 'BLEIN', 'Mickael'],
[1503, 'Emericp', 'slam1503', 'emeric.poiseau@gmail.com', 'POISEAU', 'Emeric'],
[1506, 'jeromev', 'slam1506', 'jeromevieira@free.fr', 'VIEIRA', 'Jerome'],
[1509, 'barbara', 'slam1509', 'dargaud.barbara@gmail.com', 'DARGAUD', 'Barbara'],
[1511, 'gujaillon', 'slam1511', 'guillaume.jaillon@gmail.com', 'JAILLON', 'Guillaume'],
[1512, 'guvrancken', 'slam1512', 'gus.vrancken@gmail.com', 'VRANCKEN', 'Gus'],
[1513, 'nicolasa', 'slam1513', 'nicolas.amodis.na@gmail.com', 'AMODIS', 'Nicolas'],
[1515, 'alexisv', 'slam1515', 'a.voizard@lecedre.fr', 'VOIZARD', 'Alexis'],
[1516, 'jarry.christophe@wanadoo.fr', 'slam1516', 'jarry.christophe@wanadoo.fr', 'JARRY', 'Christophe'],
[1517, 'Geoffroy Canard', 'AwZxEcRvTbYn', 'geoffroy.canard@gmail.com', 'CANARD', 'Geoffroy'],
[1523, 'nicolas amadis', 'slam1523', 'nicolas.amadis.na@gmail.com', 'AMADIS', 'Nicolas'],
[1524, 'benjaminl', 'slam1524', 'lecurub@yahoo.fr', 'LECURU', 'Benjamin'],
[1525, 'quentinb', 'slam1525', 'qbifgamdiglia@gmail.com', 'BIFGAMDIGLIA', 'Quentin'],
[1529, 'flog', 'slam1529', 'flo.g71@hotmail.fr', 'GUIGNARD', 'Florian'],
[1530, 'davidt', 'slam1530', 'tex.om@wanadoo.fr', 'TEXEIRA', 'David'],
[1531, 'romain', 'slam1531', 'romaincorneloup@hotmail.fr', 'CORNELOUP', 'Romain'],
[1532, 'etiennef', 'slam1532', 'petre71600@hotmail.fr', 'FEDRIGO', 'Etienne'],
[1534, 'LucieCarceller', 'slam1534', 'slam-1534@slam-data.net', 'CARCELLER', 'Lucie'],
[1535, 'vincentc', 'slam1535', 'vincentcostacoach@gmail.com', 'COSTA', 'Vincent'],
[1536, 'remic', 'slam1536', 'remi.chapelier@yahoo.fr', 'CHAPELIER', 'Remi'],
[1537, 'williaml', 'slam1537', 'william.labaune@wanadoo.fr', 'LABAUNE', 'William'],
[1545, 'mathieuforge', 'slam1545', 'mathieu.forge@hotmail.fr', 'FORGE', 'Mathieu'],
[1554, 'alex.phan@outlook.fr', 'slam1554', 'alex.phan@outlook.fr', 'PHAN', 'Alex'],
[1558, 'benoitj', 'slam1558', 'benoit-jouanneau@orange.fr', 'JOUANNEAU', 'Benoit'],
[1559, 'oliviav', 'slam1559', 'panification@orange.fr', 'VALLEE', 'Olivia'],
[1560, 'nicolasb', 'jenk', 'nicolasbignon@orange.fr', 'BIGNON', 'Nicolas'],
[1563, 'Réjane', 'slam1563', 'rejane.m@hotmail.fr', 'M', 'Rejane'],
[1564, 'carlos.marques@efiautomotive.com', 'slam1564', 'carlos.marques@efiautomotive.com', 'MARQUES', 'Carlos'],
[1572, 'julienb', 'slam1572', 'bouillonj@ymail.com', 'BOUILLON', 'Julien'],
[1573, 'jeff', 'slam1573', 'jeffmaillot@sfr.fr', 'MAILLOT', 'J.francois'],
[1574, 'benjaminv', 'slam1574', 'benj777@free.fr', 'VIGNOLAT', 'Benjamin'],
[1578, 'valentinb', 'slam1578', 'slam-1578@slam-data.net', 'BALIGAND', 'Valentin'],
[1579, 'ricard51', 'slam1579', 'bertrand.bornet@hotmail.fr', 'BORNET', 'Bertrand'],
[1580, 'Touillonyannick', 'slam1580', 'yannick.touillon@laposte.net', 'TOUILLON', 'Yannick'],
[1581, 'diane84', 'slam1581', 'pautonnier.jeremy@orange.fr', 'PAUTONNIER', 'Jeremy'],
[1583, 'jifiji', 'slam1583', 'jphv71@hotmail.com', 'VILLEDEY', 'Jean philippe'],
[1584, 'SKY', 'slam1584', 'skinziger@antipode-consulting.com', 'KINZIGER', 'Stephane'],
[1588, 'alexrsv4@gmail.com', 'alexrsv4', 'alexrsv4@gmail.com', 'COURTOIS', 'Alexandre'],
[1593, 'PhilippeBossut', 'slam1593', 'slam-1593@slam-data.net', 'BOSSUT', 'Philippe'],
[1597, 'stephelec', 'slam1597', 'stephane.elec08@gmail.com', 'ELEC', 'Stéphane'],
[1600, 'valentin debarnot', 'slam1600', 'valentin.debarnot@gmail.com', 'DEBARNOT', 'Valentin'],
[1601, 'jbducloux', 'slam1601', 'jbducloux@yahoo.com', 'DUCLOUX', 'J-B'],
[1611, 'alexis31', 'slam1611', 'alexlecussan@hotmail.fr', 'LECUSSAN', 'Alex'],
[1612, 'alexcussan', 'slam1612', 'alexcussan@hotmail.fr', 'LECUSSANT', 'Alexis'],
[1613, 'alexia', 'slam1613', 'alexiagioana@yahoo.fr', 'GIOANA', 'Alexia'],
[1618, 'guillaumem', 'slam1618', 'mouraux.guillaume@gmail.com', 'MOURAUX', 'Guillaume'],
[1620, 'jmpenfornis@rtsys.fr', 'slam1620', 'jmpenfornis@rtsys.fr', 'PENFORNIS', 'J-M'],
[1624, 'Hippolyte', 'slam1624', 'efoltete@gmail.com', 'FOLTETE', 'Hippolyte'],
[1625, 'Aurélien', 'slam1625', 'aurelienjacot@orange.fr', 'JACOT', 'Aurelien'],
[1626, 'Delly', 'slam1626', 'delphine.guinand@neuf.fr', 'GUINAND', 'Delphine'],
[1630, 'KAZAK', 'slam1630', 'kazak.annick@club-internet.fr', 'KAZAK', 'Annick'],
[1632, 'fmartin2570', 'slam1632', 'f.martin@artemis-paysages.fr', 'MARTIN', 'Franck'],
[1633, 'seb daveiga', 'slam1633', 'seb_daveiga@hotmail.com', 'DAVEIGA', 'Seb'],
[1638, 'tennismarnay', 'slam1638', 'abcl.bailly@wanadoo.fr', 'BAILLY', 'Laurent'],
[1639, 'dumonty', 'slam1639', 'dumontyannick@orange.fr', 'DUMONT', 'Yannick'],
[1640, 'champy', 'slam1640', 'qnque@icloud.com', 'BALME', 'Ch'],
[1641, 'AnthonyMorice', 'slam1641', 'slam-1641@slam-data.net', 'MORICE', 'Anthony'],
[1642, 'GenevièveOwenjones', 'slam1642', 'slam-1642@slam-data.net', 'OWEN JONES', 'Geneviève'],
[1645, 'mamessierl', 'slam1645', 'luc.mamessier@gmail.com', 'MAMESSIER', 'Luc'],
[1646, 'karen', 'slam1646', 'karen.reignier@laposte.net', 'REIGNIER', 'Karen'],
[1650, 'j-ph25@sfr.fr', 'Ble2rIot5', 'j-ph25@sfr.fr', 'ROSNET', 'Jean-Philippe'],
[1651, 'bebes20', 'slam1651', 'berger.seb@gmail.com', 'BERGER', 'Sebastien'],
[1652, 'Matheo2000', 'slam1652', 'fcreuillot@orange.fr', 'GARNACHE', 'Matheo'],
[1653, 'familleklotz', 'slam1653', 'arianeeklotz@gmail.com', 'KLOTZ', 'Ariane'],
[1655, 'lauraM', 'slam1655', 'menetrierl@laposte.net', 'MENETRIER', 'Laura'],
[1661, 'coeffier1975', 'slam1661', 'mcoeffier76@gmail.com', 'TOULON', 'C'],
[1663, 'Baptista.v', 'slam1663', 'slam-1663@slam-data.net', 'BAPTISTA', 'V'],
[1664, 'Benard.ma', 'slam1664', 'slam-1664@slam-data.net', 'BENARD', 'MA'],
[1670, 'Fred', 'slam1670', 'frederic.duhaze@orange.fr', 'DUHAZE', 'Frederic'],
[1671, 'André', 'slam1671', 'andreduhem@orange.fr', 'DUHEM', 'André'],
[1672, 'Sandrine T', 'slam1672', 'tribouillard@wanadoo.fr', 'TRIBOUILLARD', 'S'],
[1674, 'christophes ', 'slam1674', 'christophe.senaillet@gmail.com', 'SENAILLET', 'Christophe'],
[1675, 'damien.bernardin', 'slam1675', 'damien.bernardin71600@gmail.com', 'BERNARDIN', 'Damien'],
[1678, 'bodytitane', 'slam1678', 'bodytitane@gmail.com', 'DUBUISSON', 'Emilie'],
[1682, 'i.ducray64@gmail.com', 'slam1682', 'i.ducray64@gmail.com', 'BROUTIN', 'Xavier'],
[1683, 'Luis', 'slam1683', 'jessi_25@live.fr', 'EIRA', 'Luis'],
[1684, 'annar', 'slam1684', 'racineanna@hotmail.fr', 'RACINE', 'Anna'],
[1685, 'JulienAlley', 'slam1685', 'slam-1685@slam-data.net', 'ALLEY', 'Julien'],
[1687, 'brfilloux', 'Raq1uette', 'bruno.filloux@yahoo.fr', 'FILLOUX', 'Bruno'],
[1688, 'geginet', 'slam1688', 'gerard.ginet@gmail.com', 'GINET', 'Gerard'],
[1689, 'phsergent', 'slam1689', 'filser@hotmail.com', 'SERGENT', 'Philippe'],
[1693, 'heoule', 'slam1693', 'herve.oule@alsatis.net', 'OULE', 'Herve'],
[1694, 'epericolososporgesi', 'slam1694', 'christophe.henriot@yahoo.fr', 'HENRIOT', 'Theo'],
[1696, 'richardo', 'zinzin59', 'o.richardg@gmail.com', 'RICHARD', 'O'],
[1697, 'dagainp', 'slam1697', 'philippedagain@orange.fr', 'DEGAIN', 'Philippe'],
[1698, 'Evadasilva', 'slam1698', 'charlinemulin@hotmail.fr', 'DA SILVA', 'Eva'],
[1699, 'Paul2422', 'slam1699', 'Marilyn.friant@gmail.com', 'FRIANT', 'Paul'],
[1700, 'stevens', 'slam1700', 'stevensidibe@hotmail.fr', 'SIDIBIE', 'Steven'],
[1703, 'cortof25', 'wilson', 'cortof25@yahoo.fr', 'CORNET', 'Clovis'],
[1704, 'guillaume.forgeat@yahoo.com', 'slam1704', 'guillaume.forgeat@yahoo.com', 'FORGEAT', 'Guillaume'],
[1705, 'jechenoz', 'ollivier', 'jchenoz@yahoo.fr', 'CHENOZ', 'J'],
[1707, 'elodieb', 'slam1707', 'baque.elo@gmail.com', 'BAQUE', 'Elodie'],
[1708, 'jepezi', 'slam1708', 'pezijeanphilippe@live.fr', 'PEZI', 'Jean-Philippe'],
[1709, 'julien Poncet', 'slam1709', 'julien.poncet@hotmail.fr', 'PONCET', 'Julien'],
[1718, 'JDIEN', 'slam1718', 'slam-1718@slam-data.net', 'DIEN', 'Jérôme'],
[1719, 'HugoW', 'slam1719', 's.declercq@education-et-formation.fr', 'W', 'Hugo'],
[1720, 'QuentinL', 'slam1720', 'frederic.lefebvre0030@orange.fr', 'L', 'Quentin'],
[1721, 'EvanB', 'slam1721', 'nicolas.brandel@free.fr', 'B', 'Evan'],
[1722, 'DamienB', 'slam1722', 'vsdb@free.fr', 'B', 'Damien'],
[1723, 'ArthurB', 'slam1723', 'stephanie.dumont123@free.fr', 'B', 'Arthur'],
[1724, 'Quentin B', 'slam1724', 'breesarazin@free.fr', 'B', 'Quentin'],
[1725, 'LiamM', 'slam1725', 'sandrine.saillard@laposte.net', 'M', 'Liam'],
[1726, 'AntoineA', 'slam1726', 'angibault.guillaume@orange.fr', 'A', 'Antoine'],
[1727, 'MathisD', 'slam1727', 'laurence.jobin@yahoo.fr', 'D', 'Mathis'],
[1728, 'EstebanM', 'slam1728', 'delphine.mouille@orange.fr', 'M', 'Esteban'],
[1729, 'HugoR', 'slam1729', 'nicolas.roger26@sfr.fr', 'R', 'Hugo'],
[1731, 'NicolasD', 'slam1731', 'delaroche@sfr.fr', 'D', 'Nicolas'],
[1732, 'RomainE', 'slam1732', 'ronchesv@yahoo.fr', 'E', 'Romain'],
[1733, 'NoaC', 'slam1733', 'arthurnoa@orange.fr', 'C', 'Noa'],
[1735, 'HubertR', 'slam1735', 'hubert.ricouard@bbox.fr', 'R', 'Hubert'],
[1736, 'MathiasG', 'slam1736', 'mathias.gosselin@wanadoo.fr', 'G', 'Mathias'],
[1737, 'AureleM', 'slam1737', 'nicole.marieber@laposte.net', 'M', 'Aurele'],
[1738, 'LogannG', 'slam1738', 'karine.couturier76@wanadoo.fr', 'G', 'Logann'],
[1739, 'MathieuC', 'slam1739', 'tango.charli@hotmail.fr', 'C', 'Mathieu'],
[1741, 'sandrine.bassen@orange.fr', 'slam1741', 'sandrine.bassen@orange.fr', 'BASSEN', 'Sandrine'],
[1742, 'catly84@hotmail.fr', 'slam1742', 'catly84@hotmail.fr', 'FETTIG', 'Catherine'],
[1743, 'myrdossantos@free.fr', 'slam1743', 'myrdossantos@free.fr', 'DOS SANTOS', 'Philippine'],
[1744, 'pelissiermatthieu@hotmail.fr', 'slam1744', 'pelissiermatthieu@hotmail.fr', 'PELISSIER', 'Matthieu'],
[1745, 'pcullmann@hotmail.fr', 'slam1745', 'pcullmann@hotmail.fr', 'CULLMANN', 'Pauline'],
[1747, 'axelle.moiron@free.fr', 'slam1747', 'axelle.moiron@free.fr', 'MOIRON', 'Axelle'],
[1749, 'julienr', 'slam1749', 'julienetnadia@icloud.com', 'RAVIER', 'Julien'],
[1752, 'romain.comte', 'slam1752', 'romain.comte@icloud.com', 'COMTE', 'Romain'],
[1754, 'Maximilien.Bowen@univ-savoie.fr', 'slam1754', 'Maximilien.Bowen@univ-savoie.fr', 'BOWEN', 'Maximilien'],
[1755, 'TheoB', 'slam1755', 'badouet.emmanuel@orange.fr', 'BADOUET', 'Théo'],
[1757, 'Alex', 'slam1757', 'alexandregonzales07@gmail.com', 'GONZALES', 'Alexandre'],
[1758, 'nathclay@free.fr', 'slam1758', 'nathclay@free.fr', 'CLAY', 'Nathalie'],
[1759, 'melaniefeytie@yahoo.fr', 'slam1759', 'melaniefeytie@yahoo.fr', 'FEYTIE', 'Mélanie'],
[1764, 'py.campion@gmail.com', 'slam1764', 'py.campion@gmail.com', 'CAMPION', 'Pierre-yves'],
[1765, 'MaxenceLC', 'slam1765', 'karinecaillemet.ck@free.fr', 'LC', 'Maxence'],
[1767, 'fgseve@icloud.com', 'slam1767', 'fgseve@icloud.com', 'FETTIG', 'Séverine'],
[1768, 'NOVAK', 'slam1768', 'eilvys70@franc-comtois.fr', 'DJOKOVIC', 'Novak'],
[1773, 'geoffreys', 'slam1773', 'geoffrey.setan@gmail.com', 'SETAN', 'Geoffrey'],
[1774, 'charmypi', 'slam1774', 'arthurlavocat@hotmail.fr', 'LAVOCAT', 'Arthur'],
[1775, 'racso1997', 'slam1775', 'oscar.lefort@hotmail.fr', 'LEFORT', 'Oscar'],
[1777, 'Montmessin', 'slam1777', 'eva-montmessin@orange.fr', 'MONTMESSIN', 'Eva'],
[1778, 'Nellyfchloe', 'slam1778', 'nelly_loiret@hotmail.fr', 'FRITZSCH', 'Chloe'],
[1779, 'Baloo', 'slam1779', 'nadineboh1@orange.fr', 'BOHIN', 'Jeanne'],
[1780, 'Fanny GAIFFE', '2812', 'fanny.gaiffe@hotmail.fr', 'GAIFFE', 'Fanny'],
[1781, 'DE BRITO romain', 'slam1781', 'romain.debrito@gmail.com', 'DE BRITO', 'Romain'],
[1782, 'florence', 'slam1782', 'florence71d@hotmail.fr', 'D', 'Florence'],
[1783, 'arduc', 'slam1783', 'arletteduc.ricard@gmail.com', 'DUC RICARD', 'Arlette'],
[1786, 'cgodard@rtsys.fr', 'slam1786', 'cgodard@rtsys.fr', 'GODARD', 'C'],
[1787, 'xizard@rtsys.fr', 'slam1787', 'xizard@rtsys.fr', 'IZARD', 'X'],
[1788, 'mmichaillat@rtsys.fr', 'slam1788', 'mmichaillat@rtsys.fr', 'MICHAILLAT', 'M'],
[1791, 'Piedaterre', 'slam1791', 'slam-1791@slam-data.net', 'PIEDATERRE', 'X'],
[1795, 'seroze', 'dragon07', 'sebroze@aliceadsl.fr', 'ROZE', 'Seb'],
[1801, 'mblanc', 'slam1801', 'slam-1801@slam-data.net', 'BLANC', 'Marika'],
[1804, 'NICOLAS Catherine', 'slam1804', 'slam-1804@slam-data.net', 'NICOLAS', 'Catherine'],
[1806, 'tatch01@hotmail.fr', 'slam1806', 'tatch01@hotmail.fr', 'VAN QUANG', 'Nguyen'],
[1807, 'thomasphan69120@gmail.com', 'slam1807', 'thomasphan69120@gmail.com', 'PHAN', 'Thomas'],
[1808, 'heameziane', 'slam1808', 'herve.ameziane@ac-toulouse.fr', 'AMEZIANE', 'Herve'],
[1809, 'savrancken', 'slam1809', 'sarah.vrancken@googlemail.com', 'VRANCKEN', 'Sarah'],
[1812, 'sambaumann@yahoo.fr', 'slam1812', 'sambaumann@yahoo.fr', 'BAUMANN', 'Samuel'],
[1816, 'MarkKoenig', 'slam1816', 'slam-1816@slam-data.net', 'KOENIG', 'Mark'],
[1817, 'Zabou', 'slam1817', 'isamymy@hotmail.fr', 'LANDRIEU', 'Isabelle'],
[1818, 'jc.aulas@free.fr', 'slam1818', 'jc.aulas@free.fr', 'AULAS', 'J-christophe'],
[1819, 'Damien Bailly', 'slam1819', 'damien.bailly@orange.fr', 'BAILLY', 'Damien'],
[1820, 'robin.stefanetti@orange.fr', 'slam1820', 'robin.stefanetti@orange.fr', 'STEFANETTI', 'Robin'],
[1824, 'mathilderey101187', 'slam1824', 'matmoon@hotmail.fr', 'REY', 'Mathilde'],
[1827, 'JulieFay', 'slam1827', 'slam-1827@slam-data.net', 'FAY', 'Julie'],
[1828, 'EricZapata', 'slam1828', 'slam-1828@slam-data.net', 'ZAPATA', 'Eric'],
[1829, 'gamet romain', 'slam1829', 'romain.gamet@sfr.fr', 'GAMET', 'Romain'],
[1830, 'spasco@rtsys.fr', 'slam1830', 'spasco@rtsys.fr', 'PASCO', 'S'],
[1832, 'pchene@rtsys.fr', 'slam1832', 'pchene@rtsys.fr', 'CHENE', 'P'],
[1833, 'adrienc', 'slam1833', 'adriencuffaro@live.fr', 'CUFFARO', 'Adrien'],
[1836, 'HeleneHeuillet', 'slam1836', 'slam-1836@slam-data.net', 'HEUILLET', 'Hélène'],
[1841, 'AnneJourdain', 'slam1841', 'slam-1841@slam-data.net', 'JOURDAIN', 'Anne'],
[1842, 'HeleneMerlin', 'slam1842', 'slam-1842@slam-data.net', 'MERLIN', 'Hélène'],
[1843, 'gedeschryver', 'slam1843', 'gdssama@yahoo.fr', 'GEDESCHRYVER', 'X'],
[1844, 'guroux', 'toulouse01', 'rouxguillaume@wanadoo.fr', 'ROUX', 'Guillaume'],
[1847, 'guchevalier', '.LeMonde67!', 'guilhem.chevalier@free.fr', 'CHEVALIER', 'Guilhem'],
[1848, 'MichelAssenbaum', 'slam1848', 'slam-1848@slam-data.net', 'ASSENBAUM', 'Michel'],
[1849, 'JeremyAllaoui', 'slam1849', 'slam-1849@slam-data.net', 'ALLAOUI', 'Jeremy'],
[1852, 'frbonnaure', 'slam1852', 'cevenfb@gmail.com', 'BONNAURE', 'Fr'],
[1853, 'thseigneurie', 'AudiA3audia3', 'th.seigneurie@orange.fr', 'SEIGNEURIE', 'Th'],
[1854, 'Tutu52', 'slam1854', 'tutu52526@hotmail.fr', 'TENDAVARAYEN', 'Yoan'],
[1857, 'TANGUY', 'FLN16tgy&', 'ftanguy@rtsys.fr', 'TANGUY', 'F'],
[1858, 'delangle.a', 'slam1858', 'slam-1858@slam-data.net', 'DELANGLE', 'A'],
[1859, 'jourdan.m', 'slam1859', 'slam-1859@slam-data.net', 'JOURDAN', 'M'],
[1860, 'mafreimann', 'slam1860', 'marc.freimann@sfr.fr', 'FREIMANN', 'Marc'],
[1861, 'AudreyCalvignac', 'slam1861', 'slam-1861@slam-data.net', 'CALVIGNAC', 'Audrey'],
[1864, 'richard.journet@but.fr', 'slam1864', 'richard.journet@but.fr', 'JOURNET', 'Richard'],
[1866, 'maxim0676@live.fr ', 'slam1866', 'maxim0676@live.fr', 'ENMORINE', 'Maxime'],
[1867, 'AnneMutuel', 'slam1867', 'slam-1867@slam-data.net', 'MUTUEL', 'Anne'],
[1868, 'defontac01', '05051973', 'clement.defontaine@ac-rouen.fr', 'DEFONTAINE', 'Clement'],
[1869, 'beaunoir', 'slam1869', 'pascalbeaunoir@orange.fr', 'EAUNOIR@', 'Pascal'],
[1870, 'boudin lechat', 'botticelli', 'nathalie.boudin-lechat@ac-rouen.fr', 'BOUDIN-LECHAT', 'Nathalie'],
[1871, 'falce', 'slam1871', 'tania.falce@ac-rouen.fr', 'FALCE', 'Tania'],
[1872, 'cadenel', 'slam1872', 'jean-francois.cadenel@ac-rouen.fr', 'CADENEL', 'Jean-francois'],
[1873, 'desreumaux', 'slam1873', 'dessaj@hotmail.fr', 'DESREUMAUX', 'X'],
[1874, 'quesney', 'slam1874', 'claire.dugast@ac-rouen.fr', 'DUGAST', 'Claire'],
[1875, 'guillotel', 'slam1875', 'sebastien-domin.guillotel@ac-rouen.fr', 'GUILLOTEL', 'Sebastien-domin'],
[1876, 'mfp', 'slam1876', 'mf-poulain@orange.fr', 'POULAIN', 'Marie-Françoise'],
[1878, 'echampomier', 'slam1878', 'slam-1878@slam-data.net', 'CHAMPOMIER', 'Elina'],
[1879, 'jusse.f@laposte.net', 'slam1879', 'jusse.f@laposte.net', 'JUSSELME', 'Frederic'],
[1880, 'chliaudet', 'Liaudet1954', 'christianliaudet@orange.fr', 'LIAUDET', 'Christian'],
[1882, 'amandas@bbox.fr', 'slam1882', 'amandas@bbox.fr', 'MANDAS', 'A'],
[1883, 'MarineArnault', 'slam1883', 'slam-1883@slam-data.net', 'ARNAULT', 'Marine'],
[1885, 'FQUANTIN', 'slam1885', 'slam-1885@slam-data.net', 'QUANTIN', 'Frédéric'],
[1886, 'FADVENT', 'slam1886', 'slam-1886@slam-data.net', 'ADVENT', 'Frédéric'],
[1887, 'SMOULERES2', 'slam1887', 'slam-1887@slam-data.net', 'MOULERES', 'Stéphane'],
[1888, 'CVAZ', 'slam1888', 'slam-1888@slam-data.net', 'VAZ', 'Cédric'],
[1889, 'lsamson', 'slam1889', 'slam-1889@slam-data.net', 'SAMSON', 'Loriane'],
[1890, 'jenniferchevalier@laposte.net', 'slam1890', 'jenniferchevalier@laposte.net', 'CHEVALIER', 'Jennifer'],
[1891, 'cyril_metral@hotmail.com', 'slam1891', 'cyril_metral@hotmail.com', 'METRAL', 'Cyril'],
[1892, 'jewarthmann', 'slam1892', 'jeanmarc.warthmann@free.fr', 'WARTHMANN', 'Jean-Marc'],
[1894, 'chcanals', 'slam1894', 'christellecanals@orange.fr', 'CANALS', 'Christelle'],
[1895, 'chbenac', 'baikal', 'christophe.benac@tisseo.fr', 'BENAC', 'Christophe'],
[1899, 'sabarchechath', 's00a72m', 'samuel.barchechath@gmail.com', 'BARCHECHATH', 'Samuel'],
[1901, 'CDZ25', 'slam1901', 'pcdz25@yahoo.fr', 'CORDIEZ', 'Samuel'],
[1902, 'poussin1', 'slam1902', 'frankkamas@yahoo.fr', 'FRANCESCHINI', 'Simon'],
[1903, 'chinshiva', 'slam1903', 'chinshiva@gmail.com', 'RENAUD', 'Bastien'],
[1904, 'farfaday', 'slam1904', 'tcolson@hotmail.fr', 'COLSON', 'Thomas'],
[1905, 'Clément Barouin', 'slam1905', 'gilliard.sabrina@orange.fr', 'BAROUIN', 'Clement'],
[1907, 'freddyprost@hotmail.fr', 'slam1907', 'freddyprost@hotmail.fr', 'PROST', 'Freddy'],
[1908, 'agnes.binot@wanadoo.fr', 'slam1908', 'agnes.binot@wanadoo.fr', 'BINOT', 'Agnes'],
[1909, 'agnes.vinot@wanadoo.fr', 'slam1909', 'agnes.vinot@wanadoo.fr', 'VINOT', 'Agnes'],
[1910, 'L@miss25', 'slam1910', 'emiliedumont59@yahoo.fr', 'KISUNGU', 'Lenny'],
[1911, 'SALLAMEL', 'slam1911', 'slam-1911@slam-data.net', 'ALLAMEL', 'Simon'],
[1912, 'A.j24@orange.fr', 'slam1912', 'a.j24@orange.fr', 'JULIEN', 'Audrey'],
[1913, 'chriskass@wanadoo.fr', 'slam1913', 'chriskass@wanadoo.fr', 'JUILLET', 'Christine'],
[1916, 'tanguyp', 'slam1916', 'tanguyp9921@gmail.com', 'PERRIN', 'Tanguy'],
[1917, 'kevindacunha', 'slam1917', 'dacunha.kevin.dck@gmail.com', 'DACUNHA', 'Kevin'],
[1918, 'ZEO', 'slam1918', 'nicolas.zeo@neotek-web.com', 'ZEO', 'Nicolas'],
[1919, 'RenéCardot', 'slam1919', 'slam-1919@slam-data.net', 'CARDOT', 'Rene'],
[1920, 'DavidLamorlette', 'slam1920', 'slam-1920@slam-data.net', 'LAMORLETTE', 'David'],
[1924, 'benjaminp', 'slam1924', 'benjamin.picard@hotmail.fr', 'PICARD', 'Benjamin'],
[1925, 'Simon P', 'slam1925', 'marlene-bidoire@sfr.fr', 'PETITCUENOT', 'Simon'],
[1927, 'chsaintlary', 'slam1927', 'christophe.saint-lary@laposte.net', 'SAINT-LARY', 'Christophe'],
[1928, 'yocayeux', 'slam1928', 'y.cayeux@gmail.com', 'CAYEUX', 'Y'],
[1929, 'evelyneb', 'slam1929', 'bramard_evelyne@hotmail.fr', 'BRAMARD', 'Evelyne'],
[1930, 'mamessier', 'slam1930', 'jmamessier@cbm71.fr', 'MAMESSIER', 'J'],
[1932, 'nicomoisson@yahoo.fr', 'slam1932', 'nicomoisson@yahoo.fr', 'M', 'Nicolas'],
[1933, 'llaumbox@gmail.com', 'slam1933', 'llaumbox@gmail.com', 'M', 'Guillaume'],
[1934, 'beuvrard', 'slam1934', 'euvrard.baptiste@gmail.com', 'EUVRARD', 'Baptiste'],
[1935, 'ValérieDidaniel', 'slam1935', 'slam-1935@slam-data.net', 'DIDANIEL', 'Valérie'],
[1936, 'eandre@rtsys.fr', 'slam1936', 'eandre@rtsys.fr', 'ERWIN', 'Andre'],
[1937, 'Chavalard.arnaud@live.fr ', 'slam1937', 'chavalard.arnaud@live.fr', 'CHAVALARD', 'Arnaud'],
[1939, 'mahumbert', 'lucotte', 'marc.humbert916@orange.fr', 'HUMBERT', 'Marc'],
[1940, 'ygregoire@rtsys.fr', 'slam1940', 'ygregoire@rtsys.fr', 'GREGOIRE', 'Y'],
[1941, 'LilianM', 'slam1941', 'Jean-mi.mazier@orange.fr', 'MAZIER', 'Jean-Michel'],
[1962, 'lucasdidelle@hotmail.fr', 'slam1962', 'lucasdidelle@hotmail.fr', 'DIDELLE', 'Lucas'],
[1963, 'RBRAC@HOTMAIL.FR', 'slam1963', 'RBRAC@HOTMAIL.FR', 'RBRAC', 'X'],
[1967, 'lacombre', 'slam1967', 'lacombre.d@gmail.com', 'LACOMBRE', 'D'],
[1968, 'sylvainb', 'slam1968', 'sylvain.brize@gmail.com', 'BRIZE', 'Sylvain'],
[1969, 'maxime.bachmann@orange.fr', 'slam1969', 'maxime.bachmann@orange.fr', 'BACHMANN', 'Maxime'],
[1970, 'PatriciaGirard', 'slam1970', 'slam-1970@slam-data.net', 'GIRARD', 'Patricia'],
[1971, 'dstephane', 'slam1971', 'desbrosses.stephane@orange.fr', 'DEBROSSES', 'Stephane'],
[1974, 'Loulou2601', 'slam1974', 'loetitia62@hotmail.com', 'QUATREHOMME', 'Lou-ann'],
[1975, 'Mathis', 'slam1975', 'najuso@hotmail.fr', 'MAIREY', 'Mathis'],
[1976, 'moraisa', 'slam1976', 'alexandre-morais@hotmail.fr', 'MORAIS', 'Alexandre'],
[1979, 'jfleneveu@rtsys.fr', 'slam1979', 'jfleneveu@rtsys.fr', 'LENEVEU', 'J-F'],
[1981, 'PEYREGNE', 'slam1981', 'slam-1981@slam-data.net', 'PEYREGNE', 'X'],
[1983, 'jecarriere', 'slam1983', 'jean.carriere3@wanadoo.fr', 'CARRIERE', 'Jean'],
[1984, 'gontrand02', 'slam1984', 'slam-1984@slam-data.net', 'COULET', 'Gontrand'],
[1985, 'Baptou28', 'slam1985', 'b.martin2810@icloud.com', 'MARTIN', 'Baptiste'],
[1986, 'KEVINTENNIS', 'slam1986', 'kevin.marsot@orange.fr', 'MARSOT', 'Kevin'],
[1987, 'arbartels', 'slam1987', 'arnd.b@rtels.eu', 'ARND', 'B'],
[1988, 'pibartels', 'Louvetaux31', 'pierre.bartels@hotmail.fr', 'BARTELS', 'Pierre'],
[1989, 'jebascou', 'SteFoy31', 'jean-jacques.bascou@orange.fr', 'BASCOU', 'Jean-jacques'],
[1990, 'jecazelles', 'slam1990', 'cazelles.jeanphilippe@gmail.com', 'CAZELLES', 'Jeanphilippe'],
[1991, 'tennisarcenciel', 'slam1991', 'sebastiao.nunesdasilva@hotmail.fr', 'NUNESDASILVA', 'Sebastiao'],
[1992, 'sdesbrosses', 'slam1992', 'sdesbrosses@bouyer-leroux.fr', 'DESBROSSES', 'Stéphane'],
[1993, 'LESAUSSE.G', 'slam1993', 'slam-1993@slam-data.net', 'LESAUSSE', 'G'],
[1994, 'EBHENGA.A', 'slam1994', 'slam-1994@slam-data.net', 'EBHENGA', 'A'],
[1995, 'AudelineEscande', 'slam1995', 'slam-1995@slam-data.net', 'ESCANDE', 'Audeline'],
[1998, 'rathierquentin71@gmail.com', 'slam1998', 'rathierquentin71@gmail.com', 'RATHIER', 'Quentin'],
[1999, 'WilfriedDozeville', 'slam1999', 'slam-1999@slam-data.net', 'DOZEVILLE', 'Wilfried'],
[2000, 'CarolineBaskaya', 'slam2000', 'slam-2000@slam-data.net', 'BASKAYA', 'Caroline'],
[2001, 'AntoineDigout', 'slam2001', 'slam-2001@slam-data.net', 'DIGOUT', 'Antoine'],
[2002, 'JérômeDuchanoy', 'slam2002', 'slam-2002@slam-data.net', 'DUCHANOY', 'Jérôme'],
[2003, 'NathalieSoulages', 'slam2003', 'slam-2003@slam-data.net', 'SOULAGES', 'Nathalie'],
[2004, 'PaulineCurtan', 'slam2004', 'slam-2004@slam-data.net', 'CURTAN', 'Pauline'],
	];
    }
    

	private function getOrganisationData(): array
    {
	return [
		// $userData = [id, username, password, email, lastName, firstName, uniqueName]
[527, 'PLANNING RTSYS - NEOTEK', 'slam527', 'rtsys@rtsys.fr', 'X', 'X', 'PLANNING RTSYS - NEOTEK'],
[530, 'neotek@neotek-web.com', 'slam530', 'neotek@neotek-web.com', 'X', 'X', 'NEOTEK'],
[861, 'ecoledetennis', 'slam861', 'slam-861@slam-data.net', 'X', 'X', 'Ecole de Tennis'],
[862, 'entrainementsadultes', 'slam862', 'slam-862@slam-data.net', 'X', 'X', 'Entrainements Adultes'],
[1022, 'multimédia-SC', 'slam1022', 'piel.l@moka-sacrecoeur.fr', 'PIEL', 'L', 'Sacré Coeur'],
[1077, 'ARC', 'slam1077', 'marnaytennis@gmail.com', 'X', 'X', 'ARC-EN-CIEL'],
[1095, 'aeroclub_de_gray', 'DR340', 'sommerjeanluc@gmail.com', 'SOMMER', 'Jean-Luc', 'aeroclub_de_gray'],
[1139, 'LePlanB', 'slam1139', 'laure.desconseil@gmail.com', 'DESCONSEIL', 'Laure', 'LePlanB'],
[1158, 'titi', 'slam1158', 'slam-1158@slam-data.net', 'X', 'X', 'toto'],
[1160, 'DOKI', 'slam1160', 'philippe.chenevier@wanadoo.fr', 'CHENEVIER', 'Philippe', 'doki'],
[1161, 'babou', 'slam1161', 'slam-1161@slam-data.net', 'X', 'X', 'babou'],
[1191, 'vajallet', 'slam1191', 'mpmaffre@wanadoo.fr', 'X', 'X', 'vajallet'],
[1192, 'jelagrange', 'slam1192', 'pierre497@infonie.fr', 'X', 'X', 'jelagrange'],
[1242, 'nidotreppe', 'nico0123', 'dotreppetoulouse@gmail.com', 'X', 'X', 'nidotreppe'],
[1308, 'clhutin', 'slam1308', 'felix3110@gmail.com', 'X', 'X', 'clhutin'],
[1405, 'EUSTACHE', 'slam1405', 'slam-1405@slam-data.net', 'X', 'X', 'EUSTACHE'],
[1406, 'S_PLOUZENNEC', 'slam1406', 'slam-1406@slam-data.net', 'X', 'X', 'PLOUZENNEC'],
[1408, 'bullincharolais', 'slam1408', 'bullincharolais@gmail.com', 'X', 'X', 'bullin'],
[1416, 'zacetlili', 'massillia1993', 'zacetlili@gmail.com', 'X', 'X', 'Bouchareb'],
[1418, 'jb', '1479slam', 'jananive79@gmail.com', 'X', 'X', 'jb'],
[1420, 'scassel', 'slam1420', 'slam-1420@slam-data.net', 'X', 'X', 'Scassel'],
[1429, 'ext', 'slam1429', 'slam-1429@slam-data.net', 'X', 'X', 'ext'],
[1430, 'crivemale', 'slam1430', 'slam-1430@slam-data.net', 'X', 'X', 'crivemale'],
[1475, 'millenium71600', 'slam1475', 'samisilver@hotmail.com', 'X', 'X', 'samisilver'],
[1505, 'nad71', 'slam1505', 'cabinet.djemaa@gmail.com', 'X', 'X', 'nad'],
[1507, 'nico', 'slam1507', 'bethycarli@orange.fr', 'X', 'X', 'nicolas'],
[1546, 'marwa', 'slam1546', 'fly1977@sfr.fr', 'X', 'X', 'lahbaka'],
[1553, 'mideoliveira', 'slam1553', 'mickael127@hotmail.com', 'X', 'X', 'mideoliveira'],
[1570, 'Jiminy', 'slam1570', 'xprost@gmail.com', 'X', 'X', 'Zav'],
[1575, 'celinem', 'slam1575', 'rafclcfinance@gmail.com', 'X', 'X', 'celinem'],
[1602, 'KPConsulting', 'slam1602', 'corinne.bourdin@kpconsulting.fr', 'BOURDIN', 'Corinne', 'KPConsulting'],
[1604, 'KPC_CRM', 'slam1604', 'slam-1604@slam-data.net', 'X', 'X', 'KPC_CRM'],
[1605, 'KPC_FINANCE', 'slam1605', 'slam-1605@slam-data.net', 'X', 'X', 'KPC_FINANCE'],
[1608, 'KPC_CRM_CALL', 'slam1608', 'slam-1608@slam-data.net', 'X', 'X', 'KPC_DIGITAL'],
[1609, 'KPC_AIX', 'slam1609', 'slam-1609@slam-data.net', 'X', 'X', 'KPC_AIX'],
[1631, 'toutoun007', 'slam1631', 'mamstony71@hotmail.fr', 'X', 'X', 'mams'],
[1658, 'marwa1', 'slam1658', 'fly1977@orange.fr', 'X', 'X', 'hicham'],
[1659, 'As moi', 'slam1659', 'm_coeffier@hotmail.com', 'X', 'X', 'AS moi'],
[1686, 'frkoziol', 'slam1686', 'earl-koziol@wanadoo.fr', 'X', 'X', 'frkoziol'],
[1690, 'laonody', 'slam1690', 'lomenuiseries@free.fr', 'X', 'X', 'laonody'],
[1692, 'geoliva', 'arpete70', 'zaers@aol.com', 'X', 'X', 'geoliva'],
[1702, 'KPCAIX', 'slam1702', 'laurent.sirot@kpconsulting.fr', 'SIROT', 'Laurent', 'Conf Call KPC_AIX'],
[1740, 'ClementMathis', 'slam1740', 's_coeffier@hotmail.com', 'X', 'X', 'Clement&Mathis'],
[1748, 'rityman', 'slam1748', 'rityman2@gmail.com', 'X', 'X', 'Mirly'],
[1769, 'Sibille', 'slam1769', 'gabriel.sibille@hotmail.fr', 'X', 'X', 'Flo'],
[1800, 'bambi15', 'slam1800', 'demirema@hotmail.com', 'X', 'X', 'Bambi15'],
[1893, 'xahelle', 'slam1893', 'xh3198@gmail.com', 'X', 'X', 'xahelle'],
[1896, 'mabrocas', 'slam1896', 'thoux32@sfr.fr', 'X', 'X', 'mabrocas'],
[1897, 'daabadie', 'slam1897', 'd.abadie32@gmail.com', 'X', 'X', 'daabadie'],
[1906, 'famillegoncalves4', 'slam1906', 'fonctionair@hotmail.com', 'X', 'X', 'famillegoncalves'],
[1926, 'mf', 'slam1926', 'slam-1926@slam-data.net', 'X', 'X', 'Maintenance_informatique'],
	];
    }
}
